openapi: 3.1.0
info:
  title: Storage
  version: 3.18.3
tags:
- description: '<p>IPFS is a distributed file storage. You can store data to IPFS
    and read from them.</p>

    '
  name: IPFS
- description: '<p>You can store data records on the blockchain. A record is stored
    permanently: it cannot be changed,

    deleted, or modified by anyone and will be stored on the blockchain forever.

    '
  name: Blockchain storage
servers:
- url: https://api.tatum.io
paths:
  /v3/record:
    post:
      $ref: categories/storage/paths/v3_record_post.yml
    get:
      $ref: categories/storage/paths/v3_record_get.yml
  /v3/ipfs/{id}:
    get:
      $ref: categories/storage/paths/v3_ipfs_{id}_get.yml
  /v3/ipfs:
    post:
      $ref: categories/storage/paths/v3_ipfs_post.yml
