type: object
properties:
  fromAccount:
    maxLength: 34
    minLength: 33
    description: XRP account address. Must be the one used for generating deposit
      tags.
    example: rPRxSZzTFd6Yez3UMxFUPJvnhUhjewpjfV
    type: string
  signatureId:
    type: string
    format: uuid
    example: 26d3883e-4e17-48b3-a0ee-09a3e484ac83
    description: Identifier of the private key associated in signing application.
      Secret or signature Id must be present.
  fee:
    description: Fee to be paid, in XRP. If omitted, current fee will be calculated.
    example: '10000'
    pattern: ^[+]?((\d+(\.\d*)?)|(\.\d+))$
    type: string
  rippling:
    description: Should be true, if an account is the issuer of assets.
    example: true
    type: boolean
  requireDestinationTag:
    description: Should be true, if an account should support off-chain processing.
    example: true
    type: boolean
required:
- fromAccount
- signatureId
